# Generated by Django 5.0.6 on 2024-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
