# Generated by Django 5.0 on 2024-05-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profilepersonal_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='phone_number',
            field=models.CharField(default=9999999999, max_length=10),
        ),
    ]
