# Generated by Django 5.0 on 2024-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profilepersonal_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
