# Generated by Django 5.0 on 2024-05-30 13:42
from django.db import migrations

def set_vendor_id_for_existing_profiles(apps, schema_editor):
    ProfilePersonal = apps.get_model('users', 'ProfilePersonal')
    for profile in ProfilePersonal.objects.all():
        profile.vendor_id = profile.user.pk
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profilepersonal_vendor_id'),
    ]


    operations = [
        migrations.RunPython(set_vendor_id_for_existing_profiles),
    ]



