# Generated by Django 5.0 on 2024-05-30 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='account_type',
            field=models.CharField(choices=[('business', 'Business Account'), ('individual', 'Individual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='business_type',
            field=models.CharField(choices=[('B2B', 'B2B'), ('Digital Goods', 'Digital Goods'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Financial Services', 'Financial Services'), ('Food and Beverages', 'Food and Beverages'), ('Gaming', 'Gaming'), ('Government', 'Government'), ('Grocery', 'Grocery'), ('Health care', 'Health care'), ('Insurance', 'Insurance'), ('Jewellery', 'Jewellery'), ('NBFCs/Organizations into Lending', 'NBFCs/Organizations into Lending'), ('Logistics', 'Logistics'), ('Miscellaneous', 'Miscellaneous'), ('Mutual funds/Broking', 'Mutual funds/Broking'), ('Non Profit/NGO', 'Non Profit/NGO'), ('Online Gaming', 'Online Gaming'), ('Open and Semi Open Wallet', 'Open and Semi Open Wallet'), ('Pan shop', 'Pan shop'), ('Pharmacy', 'Pharmacy'), ('Readymade', 'Readymade'), ('Real Estate, Housing, Rentals', 'Real Estate, Housing, Rentals'), ('Retail and Shopping', 'Retail and Shopping'), ('SaaS', 'SaaS'), ('Social Media and Entertainment', 'Social Media and Entertainment'), ('Society/Trust/Club/Association', 'Society/Trust/Club/Association'), ('Telecom', 'Telecom'), ('Travel and Hospitality', 'Travel and Hospitality'), ('Utilities', 'Utilities'), ('Chit Funds', 'Chit Funds'), ('Web host/Domain seller', 'Web host/Domain seller'), ('Professional Services', 'Professional Services (Doctors, Lawyers, Architects, CAs, and other Professionals)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gst_number',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid GST number format')]),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='pan_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$', 'Invalid PAN number format')]),
        ),
    ]
