# Generated by Django 5.0 on 2024-05-31 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_kyc_account_type_alter_kyc_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$', 'Invalid PAN number format')]),
        ),
    ]
