# Generated by Django 5.0 on 2024-05-31 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_kyc_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='pan_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$', 'Invalid PAN number format')]),
        ),
    ]
