# Generated by Django 5.0 on 2024-06-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_kyc_account_number_kyc_ifsc_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='account_number',
            new_name='bank_account_number',
        ),
    ]
