# Generated by Django 5.0 on 2024-06-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('user', 'User'), ('ngo', 'NGO')], default='viewer', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
