# Generated by Django 5.0 on 2024-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customuser_category_customuser_first_time_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('user', 'User'), ('ngo', 'NGO')], default='User', max_length=50)),
                ('first_time_login', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
