# Generated by Django 5.0 on 2024-06-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userdefine_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdefine',
        ),
    ]
