# Generated by Django 5.0 on 2024-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userdefine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefine',
            name='category',
            field=models.CharField(choices=[('user', 'User'), ('ngo', 'NGO')], default='User', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdefine',
            name='first_time_login',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
