# Generated by Django 5.0 on 2024-06-06 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_allowedtag_ngodetail_taggedngo_ngodetail_ngo_causes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodetail',
            name='Logo',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_country',
            field=models.CharField(choices=[('IN', 'India')], default='IN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_founded_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2999)]),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_pin_code',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{2}\\s{0,1}[0-9]{3}$', 'Invalid PIN code format')]),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_state',
            field=models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CG', 'Chhattisgarh'), ('DN', 'Dadra and Nagar Haveli and Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], default='TS', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ngodetail',
            name='mission_statement',
            field=models.TextField(null=True),
        ),
    ]
