# Generated by Django 5.0 on 2024-06-07 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_ngodetail_ngo_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_founded_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2999)]),
        ),
          migrations.AlterField(
            model_name='ngodetail',
            name='NGO_founded_year',
            field=models.CharField(max_length=4, null=True, blank=True),  # Allow null
        ),
    ]
