# Generated by Django 5.0 on 2024-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_ngodetail_ngo_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_founded_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
