# Generated by Django 5.0 on 2024-06-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_ngodetail_ngo_founded_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngodetail',
            old_name='NGO_found_year',
            new_name='NGO_founded_year',
        ),
    ]
