# Generated by Django 5.0 on 2024-06-07 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_ngodetail_ngo_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodetail',
            name='NGO_founded_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2999)]),
        ),
    ]
