# Generated by Django 5.0 on 2024-06-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_ngodetail_ngo_founded_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngodetail',
            name='NGO_founded_year',
        ),
    ]
