# Generated by Django 5.0 on 2024-06-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_causes_ngodetail_causes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedngo',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='ngodetail',
            name='NGO_causes',
        ),
        migrations.RemoveField(
            model_name='taggedngo',
            name='content_object',
        ),
        migrations.DeleteModel(
            name='AllowedTag',
        ),
        migrations.DeleteModel(
            name='TaggedNGO',
        ),
    ]
