# Generated by Django 5.0 on 2024-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_taggedngo_tag_remove_ngodetail_ngo_causes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='bank_full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
