# Generated by Django 5.0 on 2024-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_kyc_bank_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
