# Generated by Django 5.0 on 2024-06-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_profilepersonal_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodetail',
            name='Logo',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
