# Generated by Django 5.0.6 on 2024-05-17 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('info', models.TextField()),
                ('category', models.CharField(choices=[('medical_emergency', 'Medical_Emergency'), ('healthandwellness', 'Health and Wellness'), ('education', 'Education and Learning'), ('poverty', 'Poverty Alleviation'), ('community', 'Community Development'), ('humanitarian', 'Humanitarian Aid'), ('arts', 'Arts & Culture'), ('women', 'Women Welfare'), ('child', 'Child Welfare'), ('elders', 'Elderly Care'), ('environment', 'Environmental Conservation'), ('hunger', 'Food Security'), ('speciallyabled', 'Specially Abled')], max_length=20)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
