# Generated by Django 5.0 on 2024-05-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='info',
            new_name='story',
        ),
    ]
