# Generated by Django 5.0 on 2024-05-31 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_info_donation_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='donations.donation')),
            ],
        ),
    ]
