# Generated by Django 5.0 on 2024-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
